//! Interactive first-run setup: vault path, starter config, API keys → .env.
//! Design rules: never rewrite an existing construct.toml; never echo a key;
//! .env is always chmod 600. `--non-interactive` makes this scriptable.
use anyhow::Context;
use std::path::{Path, PathBuf};

/// One promptable API key.
pub struct KeySpec {
    pub env: &'static str,
    pub label: &'static str,
}

/// Keys worth prompting for: anything the loaded config references via
/// api_key_env, plus the well-known set for features the user may enable
/// later.
pub fn key_specs(cfg: Option<&construct_config::Config>) -> Vec<KeySpec> {
    let mut keys = vec![KeySpec {
        env: "TAVILY_API_KEY",
        label: "Tavily (web search)",
    }];
    if let Some(cfg) = cfg {
        if let Some(ws) = &cfg.tools.web_search {
            if !keys.iter().any(|k| k.env == ws.api_key_env) {
                // Config names a custom env var: prompt for that instead.
                keys.insert(
                    0,
                    KeySpec {
                        env: Box::leak(ws.api_key_env.clone().into_boxed_str()),
                        label: "web search",
                    },
                );
            }
        }
    }
    keys
}

/// Pure: add or replace KEY=VALUE in .env content, preserving everything else.
pub fn upsert_env(existing: &str, key: &str, value: &str) -> String {
    let prefix = format!("{key}=");
    let mut found = false;
    let mut lines: Vec<String> = existing
        .lines()
        .map(|l| {
            if l.starts_with(&prefix) {
                found = true;
                format!("{key}={value}")
            } else {
                l.to_string()
            }
        })
        .collect();
    if !found {
        lines.push(format!("{key}={value}"));
    }
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// TOML basic-string escaping: a value like `My "Notes"` must not produce an
/// unparseable config.
fn toml_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Everything `construct setup` collects to write a complete, ready-to-run config
/// so the user never has to hand-edit the TOML.
pub struct ConfigAnswers {
    pub vault: String,
    pub inbox_folder: String,
    pub idle_minutes: u64,
    /// "ollama" | "anthropic" | "openai".
    pub provider: String,
    pub base_url: String,
    pub model: String,
    /// Env-var NAME holding the API key (cloud providers only).
    pub api_key_env: Option<String>,
}

impl ConfigAnswers {
    /// Sensible local-first defaults (Ollama on localhost), used by the
    /// non-interactive path and as the basis for interactive prompts.
    pub fn defaults(vault: String, inbox_folder: String) -> Self {
        ConfigAnswers {
            vault,
            inbox_folder,
            idle_minutes: 30,
            provider: "ollama".into(),
            base_url: "http://localhost:11434".into(),
            model: "qwen2.5:7b".into(),
            api_key_env: None,
        }
    }
}

/// Render a complete config.toml from the collected answers. Both agents share the
/// chosen provider/model/URL (and API-key env, for cloud). Pure → unit-testable.
pub fn render_config(a: &ConfigAnswers) -> String {
    let api_line = match &a.api_key_env {
        Some(env) => format!("\napi_key_env = \"{}\"", toml_escape(env)),
        None => String::new(),
    };
    let agent = |name: &str, domain: &str, tools: &str, prompt: &str| {
        format!(
            "[[agents]]\nname = \"{name}\"\ndomain = \"{domain}\"\nprovider = \"{provider}\"\n\
             model = \"{model}\"\nbase_url = \"{base}\"\ntools = {tools}\n\
             system_prompt_file = \"{prompt}\"{api_line}\n",
            provider = toml_escape(&a.provider),
            model = toml_escape(&a.model),
            base = toml_escape(&a.base_url),
        )
    };
    format!(
        r#"# Generated by `construct setup`. You can re-run setup or use the watch TUI
# (press `e`) to change any of this — no need to hand-edit.

[construct]
name = "The Construct"

[vault]
path = "{vault}"
managed_folder = "Construct"

# Web search backend (only needed for the `research-this` handler).
[tools.web_search]
backend = "tavily"
api_key_env = "TAVILY_API_KEY"

{scout}
{librarian}
# --- The three handlers ---
[[rules]]
match_tag = "theconstruct/remind-me"
agent = "Librarian"
pipeline = "remind-me"

[[rules]]
match_tag = "theconstruct/file-this"
agent = "Librarian"
pipeline = "file-this"

[[rules]]
match_tag = "theconstruct/research-this"
agent = "Scout"
pipeline = "research-this"

[actions.tag]
max_tags = 8

[actions.organize]
exclude_dirs = [".obsidian", ".trash"]

# Deterministic file-this routing: keywords → folder, NO model call.
[actions.file_this]
rules = [
    {{ any_of = ["kubernetes", "k8s", "docker", "terraform"], folder = "Reference" }},
    {{ any_of = ["invoice", "receipt", "budget"], folder = "Finance" }},
]

# Inbox: drop a note here and it's auto-processed after sitting idle.
[inbox]
folder = "{inbox}"
idle_minutes = {idle}
agent = "Librarian"
"#,
        vault = toml_escape(&a.vault),
        inbox = toml_escape(&a.inbox_folder),
        idle = a.idle_minutes,
        scout = agent(
            "Scout",
            "research",
            "[\"web_search\", \"web_fetch\"]",
            "prompts/scout.md"
        ),
        librarian = agent("Librarian", "notes", "[]", "prompts/librarian.md"),
    )
}

/// Back-compat helper: render a config with default (Ollama-local) settings and
/// the given vault + inbox folder. Used by the non-interactive path.
pub fn generated_config(vault_path: &str, inbox_folder: &str) -> String {
    render_config(&ConfigAnswers::defaults(
        vault_path.to_string(),
        inbox_folder.to_string(),
    ))
}

/// Editable prompt templates, embedded so they can be deployed regardless of how
/// the binary was installed. Users edit the copies in their config dir.
const PROMPT_SCOUT: &str = include_str!("../../../prompts/scout.md");
const PROMPT_LIBRARIAN: &str = include_str!("../../../prompts/librarian.md");
const PROMPT_DAILY: &str = include_str!("../../../prompts/daily_summary.md");

/// Write the prompt templates into `<home>/prompts/` (the config dir) so the
/// configured `system_prompt_file` paths resolve. Never clobbers an edited file.
fn deploy_prompts(home: &Path) -> anyhow::Result<()> {
    let dir = home.join("prompts");
    std::fs::create_dir_all(&dir)?;
    let mut wrote = 0;
    for (name, body) in [
        ("scout.md", PROMPT_SCOUT),
        ("librarian.md", PROMPT_LIBRARIAN),
        ("daily_summary.md", PROMPT_DAILY),
    ] {
        let p = dir.join(name);
        if !p.exists() {
            std::fs::write(&p, body)?;
            wrote += 1;
        }
    }
    if wrote > 0 {
        println!("  prompts: {wrote} template(s) → prompts/");
    }
    Ok(())
}

/// Write .env with owner-only permissions. Refuses to leave it looser.
pub fn write_env_file(path: &Path, contents: &str) -> anyhow::Result<()> {
    use std::io::Write;
    use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    // mode(0o600) applies at creation, so secrets never exist at umask perms;
    // the set_permissions re-assert tightens a pre-existing looser file.
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)
        .with_context(|| format!("writing {}", path.display()))?;
    f.write_all(contents.as_bytes())
        .with_context(|| format!("writing {}", path.display()))?;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
        .with_context(|| format!("chmod 600 {}", path.display()))?;
    Ok(())
}

/// Looks like an Obsidian vault (or at least an existing directory we can use).
fn validate_vault_path(input: &str) -> Result<(), String> {
    let p = PathBuf::from(shellexpand(input));
    if !p.is_dir() {
        return Err(format!("{} is not a directory", p.display()));
    }
    if !p.join(".obsidian").is_dir() {
        return Err(format!(
            "{} exists but has no .obsidian/ — enter it again to use anyway",
            p.display()
        ));
    }
    Ok(())
}

fn shellexpand(p: &str) -> String {
    if let Some(rest) = p.strip_prefix("~/") {
        if let Ok(home) = std::env::var("HOME") {
            return format!("{home}/{rest}");
        }
    }
    p.to_string()
}

pub struct SetupArgs {
    pub non_interactive: bool,
    pub vault: Option<String>,
    /// KEY=VALUE pairs.
    pub keys: Vec<String>,
}

/// Entry point. `config_path` is the resolved construct.toml path; `home` its dir.
pub async fn run_setup(config_path: &Path, home: &Path, args: SetupArgs) -> anyhow::Result<()> {
    println!("The Construct — setup");
    println!("  home:   {}", home.display());

    // A cloud LLM key collected during the config wizard, written to .env below.
    let mut pending_key: Option<(String, String)> = None;

    // --- construct.toml ---
    let existing_cfg = if config_path.exists() {
        let cfg =
            construct_config::Config::load(config_path).map_err(|e| anyhow::anyhow!("{}", e))?;
        println!(
            "  config: {} (existing — left untouched)",
            config_path.display()
        );
        Some(cfg)
    } else {
        let vault = match (&args.vault, args.non_interactive) {
            (Some(v), _) => v.clone(),
            (None, true) => anyhow::bail!("--non-interactive requires --vault on first run"),
            (None, false) => prompt_vault_path()?,
        };
        let toml = if args.non_interactive {
            generated_config(&shellexpand(&vault), "Inbox")
        } else {
            // Full guided wizard: inbox folder, LLM provider + URL/model, idle.
            let (answers, key) = collect_answers(shellexpand(&vault))?;
            pending_key = key;
            render_config(&answers)
        };
        std::fs::create_dir_all(home)?;
        std::fs::write(config_path, &toml)?;
        println!("  config: {} (created)", config_path.display());
        Some(construct_config::Config::load(config_path).map_err(|e| anyhow::anyhow!("{}", e))?)
    };

    // --- API keys → .env ---
    let env_path = home.join(".env");
    let mut env_text = std::fs::read_to_string(&env_path).unwrap_or_default();
    if let Some((name, value)) = &pending_key {
        env_text = upsert_env(&env_text, name, value);
    }
    if args.non_interactive {
        for pair in &args.keys {
            let (k, v) = pair
                .split_once('=')
                .ok_or_else(|| anyhow::anyhow!("--key expects KEY=VALUE, got '{pair}'"))?;
            env_text = upsert_env(&env_text, k.trim(), v.trim());
        }
    } else {
        for spec in key_specs(existing_cfg.as_ref()) {
            let already = std::env::var(spec.env).is_ok()
                || env_text
                    .lines()
                    .any(|l| l.starts_with(&format!("{}=", spec.env)));
            let label = if already {
                format!(
                    "{} [{}] — already set; enter to keep, or paste a new key",
                    spec.label, spec.env
                )
            } else {
                format!(
                    "{} [{}] — paste key, or enter to skip",
                    spec.label, spec.env
                )
            };
            let value: String = dialoguer::Password::new()
                .with_prompt(label)
                .allow_empty_password(true)
                .interact()?;
            if !value.trim().is_empty() {
                env_text = upsert_env(&env_text, spec.env, value.trim());
            }
        }
    }
    if !env_text.is_empty() {
        write_env_file(&env_path, &env_text)?;
        println!("  keys:   {} (mode 600)", env_path.display());
    }

    // --- Deploy editable prompt templates next to the config ---
    if let Err(e) = deploy_prompts(home) {
        eprintln!("  \u{26a0} could not deploy prompts: {e}");
    }

    // --- Seed the vault: create the Inbox folder + drop a readme guide ---
    if let Some(cfg) = &existing_cfg {
        if let Err(e) = seed_vault(cfg) {
            // Non-fatal: a bad vault path shouldn't abort an otherwise-good setup.
            eprintln!("  \u{26a0} could not seed vault: {e}");
        }
    }

    println!(
        "\nSetup complete. Next:\n  construct config-check\n  construct watch\n\nOpen \"the-construct-readme.md\" in your vault for a quick tour."
    );
    Ok(())
}

/// Ensure the Inbox folder exists and drop a `the-construct-readme.md` guide into
/// the vault root. Best-effort and non-destructive: the readme is written only if
/// absent (a user's edits are never clobbered). The vault is sacred.
fn seed_vault(cfg: &construct_config::Config) -> anyhow::Result<()> {
    let vault = PathBuf::from(shellexpand(&cfg.vault.path));
    if !vault.is_dir() {
        anyhow::bail!("vault path {} is not a directory", vault.display());
    }
    // Inbox is on by default — make sure the folder exists so drop-in works now.
    if let Some(inbox) = &cfg.inbox {
        std::fs::create_dir_all(vault.join(&inbox.folder))?;
        println!("  inbox:  {}/ (ready)", inbox.folder);
    }
    let readme = vault.join("the-construct-readme.md");
    if readme.exists() {
        println!("  readme: the-construct-readme.md (exists — left untouched)");
    } else {
        std::fs::write(&readme, readme_markdown(cfg))?;
        println!("  readme: the-construct-readme.md (created)");
    }
    Ok(())
}

/// The in-vault user guide. IMPORTANT: every example trigger tag is wrapped in
/// `inline code` so it is NOT a bare whitespace-delimited `#tag` token — otherwise
/// the watcher would treat this readme as a note to process. (The watcher detects
/// tags via `Note::tags()`, which only matches tokens that *start* with `#`.)
fn readme_markdown(cfg: &construct_config::Config) -> String {
    let tag_for = |p: &str| {
        cfg.rules
            .iter()
            .find(|r| r.pipeline == p)
            .map(|r| r.match_tag.clone())
    };
    let remind = tag_for("remind-me").unwrap_or_else(|| "theconstruct/remind-me".into());
    let file = tag_for("file-this").unwrap_or_else(|| "theconstruct/file-this".into());
    let research = tag_for("research-this").unwrap_or_else(|| "theconstruct/research-this".into());
    let inbox_folder = cfg
        .inbox
        .as_ref()
        .map(|i| i.folder.clone())
        .unwrap_or_else(|| "Inbox".into());
    let idle = cfg.inbox.as_ref().map(|i| i.idle_minutes).unwrap_or(30);

    format!(
        r#"# The Construct — how to use this vault

The Construct is running beside this vault as a quiet companion. **The folder is
the prompt:** you drop a markdown note, it reads it, does the work, and writes the
result back — handling most things with plain code and only reaching for a model
when it truly needs to.

> You can delete this note anytime — it's just a guide. The Construct won't
> re-create it unless you run `construct setup` again.

## The Inbox (the easy way)

Drop any note into the **`{inbox_folder}/`** folder. After it's sat untouched for
about {idle} minutes, The Construct enriches any links, summarizes it, tags it, and
either files it into a fitting folder or suggests one for your review. Want faster
pickup? Lower `idle_minutes` in your config.

## Tag a note (the explicit way)

Add one of these tags anywhere in a note's body and The Construct handles it:

| Put this tag in a note | What happens |
| --- | --- |
| `#{remind}` | **Reminder.** Parses "remind me to X by/at/on …" and records it. **No model — instant, works offline.** |
| `#{file}` | **File it.** Routes the note to a folder (keyword rules first; a local model only if needed). Proposed for your review. |
| `#{research}` | **Research it.** Uses a local model (+ web search if configured) to write a sourced report back into the note. |

### Try it now

Create a note that says **"Remind me to call the dentist tomorrow at 5pm"** and
tag it with `#{remind}` (type the tag yourself — it's shown in code here so this
guide doesn't get processed as a reminder). Within a moment The Construct rewrites
the note with a tidy reminder block and a due date — and tells you it did it
*without calling a model*.

## Watching it work

- `construct watch` opens a live dashboard (Activity, Recent Notes, status).
  Deterministic, no-model handling shows in bright green — that's the whole idea.
- `construct status` prints run counts and anything awaiting your review.
- `construct doctor` checks your setup (config, vault, whether Ollama is reachable).

## Good to know

- **`#{remind}` needs nothing else.** `#{file}` and `#{research}` use a local model
  via [Ollama](https://ollama.com) — start it (`ollama serve`) for those to run.
- The Construct only ever proposes folder moves for your review; it won't shuffle
  your vault behind your back.
- Settings live in your config file (`construct config-check` shows the path). The
  Inbox folder, the idle delay, the tags, and the models are all yours to change.

Happy building.
"#
    )
}

fn prompt_vault_path() -> anyhow::Result<String> {
    use dialoguer::Input;
    loop {
        let input: String = Input::new()
            .with_prompt("Path to your Obsidian vault")
            .interact_text()?;
        match validate_vault_path(&input) {
            Ok(()) => return Ok(input),
            Err(msg) => {
                eprintln!("  \u{26a0} {msg}");
                // Second consecutive identical answer = use anyway.
                let again: String = Input::new()
                    .with_prompt("Path to your Obsidian vault (repeat to confirm)")
                    .interact_text()?;
                if again == input {
                    return Ok(input);
                }
            }
        }
    }
}

/// Ask which folder to use as the Inbox (drop-zone for auto-processed notes).
/// Defaults to "Inbox". Empty input keeps the default.
fn prompt_inbox_folder() -> anyhow::Result<String> {
    use dialoguer::Input;
    let folder: String = Input::new()
        .with_prompt("Inbox folder — drop notes here to auto-process them")
        .default("Inbox".to_string())
        .interact_text()?;
    let f = folder.trim();
    Ok(if f.is_empty() {
        "Inbox".to_string()
    } else {
        f.to_string()
    })
}

/// The full guided config wizard: inbox folder, LLM provider (+ URL/model, or a
/// cloud API key), and inbox idle minutes. Returns the answers and an optional
/// `(env_name, key)` to write to .env. So no one ever has to hand-edit the TOML.
fn collect_answers(vault: String) -> anyhow::Result<(ConfigAnswers, Option<(String, String)>)> {
    use dialoguer::{Input, Select};
    let inbox_folder = prompt_inbox_folder()?;

    let providers = [
        "Ollama — local, free, no API key (recommended)",
        "Anthropic (Claude)",
        "OpenAI-compatible (OpenAI, Groq, Together, …)",
    ];
    let choice = Select::new()
        .with_prompt("Which LLM handles the model-using handlers (file-this, research-this)?")
        .items(&providers)
        .default(0)
        .interact()?;

    let mut a = ConfigAnswers::defaults(vault, inbox_folder);
    let mut key: Option<(String, String)> = None;
    match choice {
        0 => {
            a.provider = "ollama".into();
            a.base_url = Input::new()
                .with_prompt("Ollama URL (localhost, or a LAN box)")
                .default("http://localhost:11434".to_string())
                .interact_text()?;
            a.model = Input::new()
                .with_prompt("Model — run `ollama pull <model>` first")
                .default("qwen2.5:7b".to_string())
                .interact_text()?;
        }
        1 => {
            a.provider = "anthropic".into();
            a.base_url = "https://api.anthropic.com".into();
            a.model = Input::new()
                .with_prompt("Anthropic model")
                .default("claude-sonnet-4-6".to_string())
                .interact_text()?;
            a.api_key_env = Some("ANTHROPIC_API_KEY".into());
            key = prompt_optional_key("ANTHROPIC_API_KEY")?;
        }
        _ => {
            a.provider = "openai".into();
            a.base_url = Input::new()
                .with_prompt("OpenAI-compatible base URL")
                .default("https://api.openai.com".to_string())
                .interact_text()?;
            a.model = Input::new()
                .with_prompt("Model")
                .default("gpt-4o-mini".to_string())
                .interact_text()?;
            a.api_key_env = Some("OPENAI_API_KEY".into());
            key = prompt_optional_key("OPENAI_API_KEY")?;
        }
    }

    let idle: String = Input::new()
        .with_prompt("Inbox — process a note after it's been idle this many minutes")
        .default("30".to_string())
        .interact_text()?;
    a.idle_minutes = idle
        .trim()
        .parse::<u64>()
        .ok()
        .filter(|n| *n > 0)
        .unwrap_or(30);

    Ok((a, key))
}

/// Prompt (hidden) for an API key. Empty input → skip (None); the user can add it
/// to `.env` later.
fn prompt_optional_key(env: &str) -> anyhow::Result<Option<(String, String)>> {
    let value: String = dialoguer::Password::new()
        .with_prompt(format!("{env} — paste key, or enter to skip"))
        .allow_empty_password(true)
        .interact()?;
    let v = value.trim();
    Ok((!v.is_empty()).then(|| (env.to_string(), v.to_string())))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn upsert_env_adds_updates_and_preserves() {
        let out = upsert_env("", "TAVILY_API_KEY", "tvly-1");
        assert_eq!(out, "TAVILY_API_KEY=tvly-1\n");
        let out = upsert_env(&out, "OTHER", "x");
        let out = upsert_env(&out, "TAVILY_API_KEY", "tvly-2"); // replace in place
        assert_eq!(out.matches("TAVILY_API_KEY").count(), 1);
        assert!(out.contains("TAVILY_API_KEY=tvly-2"));
        assert!(out.contains("OTHER=x"));
        // Comments and unknown lines survive.
        let cur = "# my keys\nFOO=bar\n";
        let out = upsert_env(cur, "BAZ", "qux");
        assert!(out.starts_with("# my keys\nFOO=bar\n"));
        assert!(out.contains("BAZ=qux"));
    }

    #[test]
    fn config_from_template_substitutes_vault_path() {
        let toml = generated_config("/Users/example/Vault", "Inbox");
        let cfg: construct_config::Config = toml::from_str(&toml).unwrap();
        cfg.validate().unwrap();
        assert_eq!(cfg.vault.path, "/Users/example/Vault");
        assert_eq!(cfg.inbox.unwrap().folder, "Inbox");
    }

    #[test]
    fn render_config_cloud_provider_is_valid() {
        let a = ConfigAnswers {
            vault: "/v".into(),
            inbox_folder: "Inbox".into(),
            idle_minutes: 10,
            provider: "anthropic".into(),
            base_url: "https://api.anthropic.com".into(),
            model: "claude-sonnet-4-6".into(),
            api_key_env: Some("ANTHROPIC_API_KEY".into()),
        };
        let toml = render_config(&a);
        let cfg: construct_config::Config = toml::from_str(&toml).unwrap();
        cfg.validate().unwrap();
        assert_eq!(cfg.agents.len(), 2);
        assert!(cfg.agents.iter().all(|ag| ag.provider == "anthropic"));
        assert_eq!(
            cfg.agents[0].api_key_env.as_deref(),
            Some("ANTHROPIC_API_KEY")
        );
        assert_eq!(cfg.agents[0].model, "claude-sonnet-4-6");
        assert_eq!(cfg.inbox.unwrap().idle_minutes, 10);
    }

    #[test]
    fn render_config_ollama_has_no_api_key() {
        let toml = generated_config("/v", "Inbox");
        let cfg: construct_config::Config = toml::from_str(&toml).unwrap();
        cfg.validate().unwrap();
        assert!(cfg.agents.iter().all(|a| a.provider == "ollama"));
        assert!(cfg.agents.iter().all(|a| a.api_key_env.is_none()));
    }

    #[test]
    fn config_from_template_substitutes_inbox_folder() {
        let toml = generated_config("/v", "📥 Capture");
        let cfg: construct_config::Config = toml::from_str(&toml).unwrap();
        cfg.validate().unwrap();
        assert_eq!(cfg.inbox.unwrap().folder, "📥 Capture");
    }

    #[test]
    fn config_from_template_escapes_toml_special_chars() {
        let toml = generated_config(r#"/Users/m/My "Notes" Vault\x"#, "Inbox");
        let cfg: construct_config::Config = toml::from_str(&toml).unwrap();
        assert_eq!(cfg.vault.path, r#"/Users/m/My "Notes" Vault\x"#);
    }

    #[test]
    fn key_specs_collects_configured_env_names() {
        let cfg: construct_config::Config = toml::from_str(crate::commands::SAMPLE_CONFIG).unwrap();
        let keys = key_specs(Some(&cfg));
        assert!(keys.iter().any(|k| k.env == "TAVILY_API_KEY"));
        // No config yet → still suggests the known key set.
        assert!(key_specs(None).iter().any(|k| k.env == "TAVILY_API_KEY"));
    }

    #[test]
    fn readme_has_no_live_trigger_tags() {
        // The readme must never contain a bare `#tag` token, or the watcher would
        // try to process the readme itself. Parse it the way the watcher does.
        let cfg: construct_config::Config = toml::from_str(crate::commands::SAMPLE_CONFIG).unwrap();
        let md = readme_markdown(&cfg);
        let note = construct_obsidian::frontmatter::Note::parse(&md);
        assert!(
            note.tags().is_empty(),
            "readme leaked live trigger tags: {:?}",
            note.tags()
        );
        // Sanity: it does still mention the tags (inside backticks).
        assert!(md.contains("remind-me"));
    }

    #[tokio::test]
    async fn non_interactive_setup_creates_config_and_env_600() {
        let tmp = tempfile::tempdir().unwrap();
        let vault = tmp.path().join("Vault");
        std::fs::create_dir_all(vault.join(".obsidian")).unwrap();
        let home = tmp.path().join("home");
        let config = home.join("construct.toml");

        run_setup(
            &config,
            &home,
            SetupArgs {
                non_interactive: true,
                vault: Some(vault.to_string_lossy().to_string()),
                keys: vec!["TAVILY_API_KEY=tvly-test".into()],
            },
        )
        .await
        .unwrap();

        let cfg = construct_config::Config::load(&config).unwrap();
        assert_eq!(cfg.vault.path, vault.to_string_lossy());
        let env_path = home.join(".env");
        assert!(std::fs::read_to_string(&env_path)
            .unwrap()
            .contains("TAVILY_API_KEY=tvly-test"));
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(&env_path).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600);

        // Re-run: config untouched, key replaceable.
        run_setup(
            &config,
            &home,
            SetupArgs {
                non_interactive: true,
                vault: None,
                keys: vec!["TAVILY_API_KEY=tvly-2".into()],
            },
        )
        .await
        .unwrap();
        let env = std::fs::read_to_string(&env_path).unwrap();
        assert!(env.contains("tvly-2"));
        assert_eq!(env.matches("TAVILY_API_KEY").count(), 1);
    }
}
